const faqTexts = {
  orderReview: {
    title: 'Como avaliar um pedido?',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus vestibulum libero, id facilisis mi iaculis tristique. In hac habitasse platea dictumst. Pellentesque imperdiet luctus sem, sed malesuada sapien tempor et. Morbi rutrum, nisi at venenatis egestas, enim diam venenatis justo, ut ornare purus augue at dolor. Nam tincidunt urna eu dolor iaculis tempus. In dolor dui, facilisis id mollis ut, ultrices eu lorem. Aliquam at elit sed neque sollicitudin blandit sit amet ut dui. Aenean suscipit, leo ut pharetra interdum, nunc libero faucibus magna, ac tempus erat neque eget odio. Nulla facilisi. Mauris at fermentum nibh, eu tempus tellus. Aliquam id lacus id augue vulputate finibus. Nam non pretium erat, eu pretium diam. Mauris vel elit eu tellus dapibus ornare vel et nisi. Integer mollis commodo risus, eu hendrerit velit laoreet ut.',
  },
  orderLate: {
    title: 'Está atrasado?',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus vestibulum libero, id facilisis mi iaculis tristique. In hac habitasse platea dictumst. Pellentesque imperdiet luctus sem, sed malesuada sapien tempor et. Morbi rutrum, nisi at venenatis egestas, enim diam venenatis justo, ut ornare purus augue at dolor. Nam tincidunt urna eu dolor iaculis tempus. In dolor dui, facilisis id mollis ut, ultrices eu lorem. Aliquam at elit sed neque sollicitudin blandit sit amet ut dui. Aenean suscipit, leo ut pharetra interdum, nunc libero faucibus magna, ac tempus erat neque eget odio. Nulla facilisi. Mauris at fermentum nibh, eu tempus tellus. Aliquam id lacus id augue vulputate finibus. Nam non pretium erat, eu pretium diam. Mauris vel elit eu tellus dapibus ornare vel et nisi. Integer mollis commodo risus, eu hendrerit velit laoreet ut.',
  },
  orderMissing: {
    title: 'O pedido chegou errado ou está faltando itens?',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus vestibulum libero, id facilisis mi iaculis tristique. In hac habitasse platea dictumst. Pellentesque imperdiet luctus sem, sed malesuada sapien tempor et. Morbi rutrum, nisi at venenatis egestas, enim diam venenatis justo, ut ornare purus augue at dolor. Nam tincidunt urna eu dolor iaculis tempus. In dolor dui, facilisis id mollis ut, ultrices eu lorem. Aliquam at elit sed neque sollicitudin blandit sit amet ut dui. Aenean suscipit, leo ut pharetra interdum, nunc libero faucibus magna, ac tempus erat neque eget odio. Nulla facilisi. Mauris at fermentum nibh, eu tempus tellus. Aliquam id lacus id augue vulputate finibus. Nam non pretium erat, eu pretium diam. Mauris vel elit eu tellus dapibus ornare vel et nisi. Integer mollis commodo risus, eu hendrerit velit laoreet ut.',
  },
  cancellation: {
    title: 'Cancelamento',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus vestibulum libero, id facilisis mi iaculis tristique. In hac habitasse platea dictumst. Pellentesque imperdiet luctus sem, sed malesuada sapien tempor et. Morbi rutrum, nisi at venenatis egestas, enim diam venenatis justo, ut ornare purus augue at dolor. Nam tincidunt urna eu dolor iaculis tempus. In dolor dui, facilisis id mollis ut, ultrices eu lorem. Aliquam at elit sed neque sollicitudin blandit sit amet ut dui. Aenean suscipit, leo ut pharetra interdum, nunc libero faucibus magna, ac tempus erat neque eget odio. Nulla facilisi. Mauris at fermentum nibh, eu tempus tellus. Aliquam id lacus id augue vulputate finibus. Nam non pretium erat, eu pretium diam. Mauris vel elit eu tellus dapibus ornare vel et nisi. Integer mollis commodo risus, eu hendrerit velit laoreet ut.',
  },
  tapsterJobs: {
    title: 'Quero trabalhar na é pra já',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus vestibulum libero, id facilisis mi iaculis tristique. In hac habitasse platea dictumst. Pellentesque imperdiet luctus sem, sed malesuada sapien tempor et. Morbi rutrum, nisi at venenatis egestas, enim diam venenatis justo, ut ornare purus augue at dolor. Nam tincidunt urna eu dolor iaculis tempus. In dolor dui, facilisis id mollis ut, ultrices eu lorem. Aliquam at elit sed neque sollicitudin blandit sit amet ut dui. Aenean suscipit, leo ut pharetra interdum, nunc libero faucibus magna, ac tempus erat neque eget odio. Nulla facilisi. Mauris at fermentum nibh, eu tempus tellus. Aliquam id lacus id augue vulputate finibus. Nam non pretium erat, eu pretium diam. Mauris vel elit eu tellus dapibus ornare vel et nisi. Integer mollis commodo risus, eu hendrerit velit laoreet ut.',
  },
  howWorks: {
    title: 'O que é? E como funciona a é pra já',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus vestibulum libero, id facilisis mi iaculis tristique. In hac habitasse platea dictumst. Pellentesque imperdiet luctus sem, sed malesuada sapien tempor et. Morbi rutrum, nisi at venenatis egestas, enim diam venenatis justo, ut ornare purus augue at dolor. Nam tincidunt urna eu dolor iaculis tempus. In dolor dui, facilisis id mollis ut, ultrices eu lorem. Aliquam at elit sed neque sollicitudin blandit sit amet ut dui. Aenean suscipit, leo ut pharetra interdum, nunc libero faucibus magna, ac tempus erat neque eget odio. Nulla facilisi. Mauris at fermentum nibh, eu tempus tellus. Aliquam id lacus id augue vulputate finibus. Nam non pretium erat, eu pretium diam. Mauris vel elit eu tellus dapibus ornare vel et nisi. Integer mollis commodo risus, eu hendrerit velit laoreet ut.',
  },
  termsOfUse: {
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempus vestibulum libero, id facilisis mi iaculis tristique. In hac habitasse platea dictumst. Pellentesque imperdiet luctus sem, sed malesuada sapien tempor et. Morbi rutrum, nisi at venenatis egestas, enim diam venenatis justo, ut ornare purus augue at dolor. Nam tincidunt urna eu dolor iaculis tempus. In dolor dui, facilisis id mollis ut, ultrices eu lorem. Aliquam at elit sed neque sollicitudin blandit sit amet ut dui. Aenean suscipit, leo ut pharetra interdum, nunc libero faucibus magna, ac tempus erat neque eget odio. Nulla facilisi. Mauris at fermentum nibh, eu tempus tellus. Aliquam id lacus id augue vulputate finibus. Nam non pretium erat, eu pretium diam. Mauris vel elit eu tellus dapibus ornare vel et nisi. Integer mollis commodo risus, eu hendrerit velit laoreet ut.',
  },
};

export default faqTexts;
